trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - .gitignore.txt
    - README.md
    - LICENSE
    - azure-pipelines-linux.yml
    - azure-pipelines-macos.yml

pool:
  vmImage: vs2017-win2016

variables:
  buildConfiguration: Release

steps:
- task: DotNetCoreInstaller@0
  inputs:
    packageType: sdk
    version: 2.1.505
  displayName: 'Upgrade .NET Core'

- script: |
    dotnet build AudioWorks\AudioWorks.sln --configuration $(buildConfiguration)
  displayName: 'Build $(buildConfiguration) configuration'

- powershell: |
    Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
    Invoke-WebRequest -Uri https://audioworks.blob.core.windows.net/prerequisites/AppleApplicationSupport.msi -OutFile AppleApplicationSupport.msi
    Invoke-WebRequest -Uri https://audioworks.blob.core.windows.net/prerequisites/AppleApplicationSupport64.msi -OutFile AppleApplicationSupport64.msi
  displayName: 'Download prerequisites'

- script: |
    COPY /Y nuget.exe %USERPROFILE%
    msiexec /i AppleApplicationSupport.msi /qb-
    msiexec /i AppleApplicationSupport64.msi /qb-
    dotnet tool install --global dotnet-reportgenerator-globaltool
  displayName: 'Install prerequisites'

- powershell: |
    $settingsDir = "$([System.Environment]::GetFolderPath(26))\AudioWorks"
    $localFeedDir = (New-Item "$settingsDir\LocalFeed" -ItemType Directory).FullName
    Get-ChildItem -Path AudioWorks\src\Extensions -Filter *.nupkg -Recurse | Select-Object -ExpandProperty FullName | % { &"$env:USERPROFILE\nuget" add $_ -Source $localFeedDir -NonInteractive }
    $content = Get-Content AudioWorks\src\AudioWorks.Common\settings.json | ConvertFrom-Json
    $content.EnableTelemetry = $false
    $content.ExtensionRepository = $localFeedDir
    $content | ConvertTo-Json | Set-Content "$settingsDir\settings.json"
    dotnet test AudioWorks\tests\AudioWorks.Api.Tests --no-build --configuration Release --filter "FullyQualifiedName=AudioWorks.Api.Tests.AudioFileTests.HasExpectedPath"
    $testResult = 0
    Get-ChildItem -Path AudioWorks\tests -Filter *.Tests -Directory | % { dotnet test $_.FullName --no-build --logger trx --framework netcoreapp2.1 --configuration $env:BUILDCONFIGURATION /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=.\coverage.netcoreapp2.1.xml /p:Exclude="[AudioWorks.*.Tests]*%2c[AudioWorks.TestUtilities]*%2c[xunit.*]*%2c[*]JetBrains.*" /p:IncludeDirectory="$settingsDir\Extensions\netcoreapp2.1\*%2c$($_.FullName)\bin\$($env:BUILDCONFIGURATION)\netcoreapp2.1\AudioWorks.Commands\netcoreapp2.1"; if ($LastExitCode -ne 0) { $testResult = $LastExitCode } }
    Get-ChildItem -Path AudioWorks\tests -Filter *.Tests -Directory | % { dotnet test $_.FullName --no-build --logger trx --framework net471 --configuration $env:BUILDCONFIGURATION /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=.\coverage.net471.xml /p:Exclude="[AudioWorks.*.Tests]*%2c[AudioWorks.TestUtilities]*%2c[xunit.*]*%2c[*]JetBrains.*" /p:IncludeDirectory="$settingsDir\Extensions\netstandard2.0\*%2c$($_.FullName)\bin\$($env:BUILDCONFIGURATION)\net471\AudioWorks.Commands\netstandard2.0"; if ($LastExitCode -ne 0) { $testResult = $LastExitCode } }
    exit $testResult
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**\*.trx'
  displayName: 'Publish test results'
  condition: succeededOrFailed()

- script: |
    reportgenerator -reports:AudioWorks\tests\*\coverage.*.xml -targetdir:Reports\Cobertura -reporttypes:Cobertura
    reportgenerator -reports:Reports\Cobertura\Cobertura.xml -targetdir:Reports\HTML "-reporttypes:HTMLInline;HTMLChart"
  displayName: 'Generate code coverage results'

- task: PublishCodeCoverageResults@1
  inputs:
    codecoverageTool: cobertura
    summaryFileLocation: $(Build.SourcesDirectory)\Reports\Cobertura\Cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)\Reports\HTML
  displayName: 'Publish code coverage results'

- task: CopyFiles@2
  inputs:
    contents: |
      AudioWorks\src\**\*.nupkg
      AudioWorks\src\**\*.snupkg
      AudioWorks\src\AudioWorks.Commands\bin\$(buildConfiguration)\AudioWorks.Commands\**
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy artifacts to staging directory'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'